call cd SCRIPT
call npm install
call cd ..
call md DOWNLOADED_DATA
call cd DOWNLOADED_DATA


call node ..\SCRIPT\Tajikistan.txt_3.js
call node ..\SCRIPT\Tajikistan.txt_2.js
call node ..\SCRIPT\Tajikistan.txt_1.js

call node ..\SCRIPT\Peru.txt_12.js
call node ..\SCRIPT\Peru.txt_11.js
call node ..\SCRIPT\Peru.txt_10.js
call node ..\SCRIPT\Peru.txt_9.js
call node ..\SCRIPT\Peru.txt_8.js
call node ..\SCRIPT\Peru.txt_7.js
call node ..\SCRIPT\Peru.txt_6.js
call node ..\SCRIPT\Peru.txt_5.js
call node ..\SCRIPT\Peru.txt_4.js
call node ..\SCRIPT\Peru.txt_3.js
call node ..\SCRIPT\Peru.txt_2.js
call node ..\SCRIPT\Peru.txt_1.js

call node ..\SCRIPT\Kenya.txt_5.js
call node ..\SCRIPT\Kenya.txt_4.js
call node ..\SCRIPT\Kenya.txt_3.js
call node ..\SCRIPT\Kenya.txt_2.js
call node ..\SCRIPT\Kenya.txt_1.js

call node ..\SCRIPT\Syria.txt_26.js
call node ..\SCRIPT\Syria.txt_25.js
call node ..\SCRIPT\Syria.txt_24.js
call node ..\SCRIPT\Syria.txt_23.js
call node ..\SCRIPT\Syria.txt_22.js
call node ..\SCRIPT\Syria.txt_21.js
call node ..\SCRIPT\Syria.txt_20.js
call node ..\SCRIPT\Syria.txt_19.js
call node ..\SCRIPT\Syria.txt_18.js
call node ..\SCRIPT\Syria.txt_17.js
call node ..\SCRIPT\Syria.txt_16.js
call node ..\SCRIPT\Syria.txt_15.js
call node ..\SCRIPT\Syria.txt_14.js
call node ..\SCRIPT\Syria.txt_13.js
call node ..\SCRIPT\Syria.txt_12.js
call node ..\SCRIPT\Syria.txt_11.js
call node ..\SCRIPT\Syria.txt_10.js
call node ..\SCRIPT\Syria.txt_9.js
call node ..\SCRIPT\Syria.txt_8.js
call node ..\SCRIPT\Syria.txt_7.js
call node ..\SCRIPT\Syria.txt_6.js
call node ..\SCRIPT\Syria.txt_5.js
call node ..\SCRIPT\Syria.txt_4.js
call node ..\SCRIPT\Syria.txt_3.js
call node ..\SCRIPT\Syria.txt_2.js
call node ..\SCRIPT\Syria.txt_1.js

call node ..\SCRIPT\Tonga.txt_14.js
call node ..\SCRIPT\Tonga.txt_13.js
call node ..\SCRIPT\Tonga.txt_12.js
call node ..\SCRIPT\Tonga.txt_11.js
call node ..\SCRIPT\Tonga.txt_10.js
call node ..\SCRIPT\Tonga.txt_9.js
call node ..\SCRIPT\Tonga.txt_8.js
call node ..\SCRIPT\Tonga.txt_7.js
call node ..\SCRIPT\Tonga.txt_6.js
call node ..\SCRIPT\Tonga.txt_5.js
call node ..\SCRIPT\Tonga.txt_4.js
call node ..\SCRIPT\Tonga.txt_3.js
call node ..\SCRIPT\Tonga.txt_2.js
call node ..\SCRIPT\Tonga.txt_1.js

call node ..\SCRIPT\Malta.txt_34.js
call node ..\SCRIPT\Malta.txt_33.js
call node ..\SCRIPT\Malta.txt_32.js
call node ..\SCRIPT\Malta.txt_31.js
call node ..\SCRIPT\Malta.txt_30.js
call node ..\SCRIPT\Malta.txt_29.js
call node ..\SCRIPT\Malta.txt_28.js
call node ..\SCRIPT\Malta.txt_27.js
call node ..\SCRIPT\Malta.txt_26.js
call node ..\SCRIPT\Malta.txt_25.js
call node ..\SCRIPT\Malta.txt_24.js
call node ..\SCRIPT\Malta.txt_23.js
call node ..\SCRIPT\Malta.txt_22.js
call node ..\SCRIPT\Malta.txt_21.js
call node ..\SCRIPT\Malta.txt_20.js
call node ..\SCRIPT\Malta.txt_19.js
call node ..\SCRIPT\Malta.txt_18.js
call node ..\SCRIPT\Malta.txt_17.js
call node ..\SCRIPT\Malta.txt_16.js
call node ..\SCRIPT\Malta.txt_15.js
call node ..\SCRIPT\Malta.txt_14.js
call node ..\SCRIPT\Malta.txt_13.js
call node ..\SCRIPT\Malta.txt_12.js
call node ..\SCRIPT\Malta.txt_11.js
call node ..\SCRIPT\Malta.txt_10.js
call node ..\SCRIPT\Malta.txt_9.js
call node ..\SCRIPT\Malta.txt_8.js
call node ..\SCRIPT\Malta.txt_7.js
call node ..\SCRIPT\Malta.txt_6.js
call node ..\SCRIPT\Malta.txt_5.js
call node ..\SCRIPT\Malta.txt_4.js
call node ..\SCRIPT\Malta.txt_3.js
call node ..\SCRIPT\Malta.txt_2.js
call node ..\SCRIPT\Malta.txt_1.js

call node ..\SCRIPT\Malaysia.txt_20.js
call node ..\SCRIPT\Malaysia.txt_19.js
call node ..\SCRIPT\Malaysia.txt_18.js
call node ..\SCRIPT\Malaysia.txt_17.js
call node ..\SCRIPT\Malaysia.txt_16.js
call node ..\SCRIPT\Malaysia.txt_15.js
call node ..\SCRIPT\Malaysia.txt_14.js
call node ..\SCRIPT\Malaysia.txt_13.js
call node ..\SCRIPT\Malaysia.txt_12.js
call node ..\SCRIPT\Malaysia.txt_11.js
call node ..\SCRIPT\Malaysia.txt_10.js
call node ..\SCRIPT\Malaysia.txt_9.js
call node ..\SCRIPT\Malaysia.txt_8.js
call node ..\SCRIPT\Malaysia.txt_7.js
call node ..\SCRIPT\Malaysia.txt_6.js
call node ..\SCRIPT\Malaysia.txt_5.js
call node ..\SCRIPT\Malaysia.txt_4.js
call node ..\SCRIPT\Malaysia.txt_3.js
call node ..\SCRIPT\Malaysia.txt_2.js
call node ..\SCRIPT\Malaysia.txt_1.js

call node ..\SCRIPT\Sudan.txt_6.js
call node ..\SCRIPT\Sudan.txt_5.js
call node ..\SCRIPT\Sudan.txt_4.js
call node ..\SCRIPT\Sudan.txt_3.js
call node ..\SCRIPT\Sudan.txt_2.js
call node ..\SCRIPT\Sudan.txt_1.js

call node ..\SCRIPT\Singapore.txt_10.js
call node ..\SCRIPT\Singapore.txt_9.js
call node ..\SCRIPT\Singapore.txt_8.js
call node ..\SCRIPT\Singapore.txt_7.js
call node ..\SCRIPT\Singapore.txt_6.js
call node ..\SCRIPT\Singapore.txt_5.js
call node ..\SCRIPT\Singapore.txt_4.js
call node ..\SCRIPT\Singapore.txt_3.js
call node ..\SCRIPT\Singapore.txt_2.js
call node ..\SCRIPT\Singapore.txt_1.js

call node ..\SCRIPT\Fiji.txt_7.js
call node ..\SCRIPT\Fiji.txt_6.js
call node ..\SCRIPT\Fiji.txt_5.js
call node ..\SCRIPT\Fiji.txt_4.js
call node ..\SCRIPT\Fiji.txt_3.js
call node ..\SCRIPT\Fiji.txt_2.js
call node ..\SCRIPT\Fiji.txt_1.js

call node ..\SCRIPT\Latvia.txt_19.js
call node ..\SCRIPT\Latvia.txt_18.js
call node ..\SCRIPT\Latvia.txt_17.js
call node ..\SCRIPT\Latvia.txt_16.js
call node ..\SCRIPT\Latvia.txt_15.js
call node ..\SCRIPT\Latvia.txt_14.js
call node ..\SCRIPT\Latvia.txt_13.js
call node ..\SCRIPT\Latvia.txt_12.js
call node ..\SCRIPT\Latvia.txt_11.js
call node ..\SCRIPT\Latvia.txt_10.js
call node ..\SCRIPT\Latvia.txt_9.js
call node ..\SCRIPT\Latvia.txt_8.js
call node ..\SCRIPT\Latvia.txt_7.js
call node ..\SCRIPT\Latvia.txt_6.js
call node ..\SCRIPT\Latvia.txt_5.js
call node ..\SCRIPT\Latvia.txt_4.js
call node ..\SCRIPT\Latvia.txt_3.js
call node ..\SCRIPT\Latvia.txt_2.js
call node ..\SCRIPT\Latvia.txt_1.js

call node ..\SCRIPT\France.txt_24.js
call node ..\SCRIPT\France.txt_23.js
call node ..\SCRIPT\France.txt_22.js
call node ..\SCRIPT\France.txt_21.js
call node ..\SCRIPT\France.txt_20.js
call node ..\SCRIPT\France.txt_19.js
call node ..\SCRIPT\France.txt_18.js
call node ..\SCRIPT\France.txt_17.js
call node ..\SCRIPT\France.txt_16.js
call node ..\SCRIPT\France.txt_15.js
call node ..\SCRIPT\France.txt_14.js
call node ..\SCRIPT\France.txt_13.js
call node ..\SCRIPT\France.txt_12.js
call node ..\SCRIPT\France.txt_11.js
call node ..\SCRIPT\France.txt_10.js
call node ..\SCRIPT\France.txt_9.js
call node ..\SCRIPT\France.txt_8.js
call node ..\SCRIPT\France.txt_7.js
call node ..\SCRIPT\France.txt_6.js
call node ..\SCRIPT\France.txt_5.js
call node ..\SCRIPT\France.txt_4.js
call node ..\SCRIPT\France.txt_3.js
call node ..\SCRIPT\France.txt_2.js
call node ..\SCRIPT\France.txt_1.js

call node ..\SCRIPT\Switzerland.txt_7.js
call node ..\SCRIPT\Switzerland.txt_6.js
call node ..\SCRIPT\Switzerland.txt_5.js
call node ..\SCRIPT\Switzerland.txt_4.js
call node ..\SCRIPT\Switzerland.txt_3.js
call node ..\SCRIPT\Switzerland.txt_2.js
call node ..\SCRIPT\Switzerland.txt_1.js

call node ..\SCRIPT\Nepal.txt_31.js
call node ..\SCRIPT\Nepal.txt_30.js
call node ..\SCRIPT\Nepal.txt_29.js
call node ..\SCRIPT\Nepal.txt_28.js
call node ..\SCRIPT\Nepal.txt_27.js
call node ..\SCRIPT\Nepal.txt_26.js
call node ..\SCRIPT\Nepal.txt_25.js
call node ..\SCRIPT\Nepal.txt_24.js
call node ..\SCRIPT\Nepal.txt_23.js
call node ..\SCRIPT\Nepal.txt_22.js
call node ..\SCRIPT\Nepal.txt_21.js
call node ..\SCRIPT\Nepal.txt_20.js
call node ..\SCRIPT\Nepal.txt_19.js
call node ..\SCRIPT\Nepal.txt_18.js
call node ..\SCRIPT\Nepal.txt_17.js
call node ..\SCRIPT\Nepal.txt_16.js
call node ..\SCRIPT\Nepal.txt_15.js
call node ..\SCRIPT\Nepal.txt_14.js
call node ..\SCRIPT\Nepal.txt_13.js
call node ..\SCRIPT\Nepal.txt_12.js
call node ..\SCRIPT\Nepal.txt_11.js
call node ..\SCRIPT\Nepal.txt_10.js
call node ..\SCRIPT\Nepal.txt_9.js
call node ..\SCRIPT\Nepal.txt_8.js
call node ..\SCRIPT\Nepal.txt_7.js
call node ..\SCRIPT\Nepal.txt_6.js
call node ..\SCRIPT\Nepal.txt_5.js
call node ..\SCRIPT\Nepal.txt_4.js
call node ..\SCRIPT\Nepal.txt_3.js
call node ..\SCRIPT\Nepal.txt_2.js
call node ..\SCRIPT\Nepal.txt_1.js

call node ..\SCRIPT\Lebanon.txt_39.js
call node ..\SCRIPT\Lebanon.txt_38.js
call node ..\SCRIPT\Lebanon.txt_37.js
call node ..\SCRIPT\Lebanon.txt_36.js
call node ..\SCRIPT\Lebanon.txt_35.js
call node ..\SCRIPT\Lebanon.txt_34.js
call node ..\SCRIPT\Lebanon.txt_33.js
call node ..\SCRIPT\Lebanon.txt_32.js
call node ..\SCRIPT\Lebanon.txt_31.js
call node ..\SCRIPT\Lebanon.txt_30.js
call node ..\SCRIPT\Lebanon.txt_29.js
call node ..\SCRIPT\Lebanon.txt_28.js
call node ..\SCRIPT\Lebanon.txt_27.js
call node ..\SCRIPT\Lebanon.txt_26.js
call node ..\SCRIPT\Lebanon.txt_25.js
call node ..\SCRIPT\Lebanon.txt_24.js
call node ..\SCRIPT\Lebanon.txt_23.js
call node ..\SCRIPT\Lebanon.txt_22.js
call node ..\SCRIPT\Lebanon.txt_21.js
call node ..\SCRIPT\Lebanon.txt_20.js
call node ..\SCRIPT\Lebanon.txt_19.js
call node ..\SCRIPT\Lebanon.txt_18.js
call node ..\SCRIPT\Lebanon.txt_17.js
call node ..\SCRIPT\Lebanon.txt_16.js
call node ..\SCRIPT\Lebanon.txt_15.js
call node ..\SCRIPT\Lebanon.txt_14.js
call node ..\SCRIPT\Lebanon.txt_13.js
call node ..\SCRIPT\Lebanon.txt_12.js
call node ..\SCRIPT\Lebanon.txt_11.js
call node ..\SCRIPT\Lebanon.txt_10.js
call node ..\SCRIPT\Lebanon.txt_9.js
call node ..\SCRIPT\Lebanon.txt_8.js
call node ..\SCRIPT\Lebanon.txt_7.js
call node ..\SCRIPT\Lebanon.txt_6.js
call node ..\SCRIPT\Lebanon.txt_5.js
call node ..\SCRIPT\Lebanon.txt_4.js
call node ..\SCRIPT\Lebanon.txt_3.js
call node ..\SCRIPT\Lebanon.txt_2.js
call node ..\SCRIPT\Lebanon.txt_1.js

call node ..\SCRIPT\Rwanda.txt_7.js
call node ..\SCRIPT\Rwanda.txt_6.js
call node ..\SCRIPT\Rwanda.txt_5.js
call node ..\SCRIPT\Rwanda.txt_4.js
call node ..\SCRIPT\Rwanda.txt_3.js
call node ..\SCRIPT\Rwanda.txt_2.js
call node ..\SCRIPT\Rwanda.txt_1.js

call node ..\SCRIPT\Slovenia.txt_28.js
call node ..\SCRIPT\Slovenia.txt_27.js
call node ..\SCRIPT\Slovenia.txt_26.js
call node ..\SCRIPT\Slovenia.txt_25.js
call node ..\SCRIPT\Slovenia.txt_24.js
call node ..\SCRIPT\Slovenia.txt_23.js
call node ..\SCRIPT\Slovenia.txt_22.js
call node ..\SCRIPT\Slovenia.txt_21.js
call node ..\SCRIPT\Slovenia.txt_20.js
call node ..\SCRIPT\Slovenia.txt_19.js
call node ..\SCRIPT\Slovenia.txt_18.js
call node ..\SCRIPT\Slovenia.txt_17.js
call node ..\SCRIPT\Slovenia.txt_16.js
call node ..\SCRIPT\Slovenia.txt_15.js
call node ..\SCRIPT\Slovenia.txt_14.js
call node ..\SCRIPT\Slovenia.txt_13.js
call node ..\SCRIPT\Slovenia.txt_12.js
call node ..\SCRIPT\Slovenia.txt_11.js
call node ..\SCRIPT\Slovenia.txt_10.js
call node ..\SCRIPT\Slovenia.txt_9.js
call node ..\SCRIPT\Slovenia.txt_8.js
call node ..\SCRIPT\Slovenia.txt_7.js
call node ..\SCRIPT\Slovenia.txt_6.js
call node ..\SCRIPT\Slovenia.txt_5.js
call node ..\SCRIPT\Slovenia.txt_4.js
call node ..\SCRIPT\Slovenia.txt_3.js
call node ..\SCRIPT\Slovenia.txt_2.js
call node ..\SCRIPT\Slovenia.txt_1.js

call node ..\SCRIPT\Serbia.txt_18.js
call node ..\SCRIPT\Serbia.txt_17.js
call node ..\SCRIPT\Serbia.txt_16.js
call node ..\SCRIPT\Serbia.txt_15.js
call node ..\SCRIPT\Serbia.txt_14.js
call node ..\SCRIPT\Serbia.txt_13.js
call node ..\SCRIPT\Serbia.txt_12.js
call node ..\SCRIPT\Serbia.txt_11.js
call node ..\SCRIPT\Serbia.txt_10.js
call node ..\SCRIPT\Serbia.txt_9.js
call node ..\SCRIPT\Serbia.txt_8.js
call node ..\SCRIPT\Serbia.txt_7.js
call node ..\SCRIPT\Serbia.txt_6.js
call node ..\SCRIPT\Serbia.txt_5.js
call node ..\SCRIPT\Serbia.txt_4.js
call node ..\SCRIPT\Serbia.txt_3.js
call node ..\SCRIPT\Serbia.txt_2.js
call node ..\SCRIPT\Serbia.txt_1.js

call node ..\SCRIPT\Italy.txt_33.js
call node ..\SCRIPT\Italy.txt_32.js
call node ..\SCRIPT\Italy.txt_31.js
call node ..\SCRIPT\Italy.txt_30.js
call node ..\SCRIPT\Italy.txt_29.js
call node ..\SCRIPT\Italy.txt_28.js
call node ..\SCRIPT\Italy.txt_27.js
call node ..\SCRIPT\Italy.txt_26.js
call node ..\SCRIPT\Italy.txt_25.js
call node ..\SCRIPT\Italy.txt_24.js
call node ..\SCRIPT\Italy.txt_23.js
call node ..\SCRIPT\Italy.txt_22.js
call node ..\SCRIPT\Italy.txt_21.js
call node ..\SCRIPT\Italy.txt_20.js
call node ..\SCRIPT\Italy.txt_19.js
call node ..\SCRIPT\Italy.txt_18.js
call node ..\SCRIPT\Italy.txt_17.js
call node ..\SCRIPT\Italy.txt_16.js
call node ..\SCRIPT\Italy.txt_15.js
call node ..\SCRIPT\Italy.txt_14.js
call node ..\SCRIPT\Italy.txt_13.js
call node ..\SCRIPT\Italy.txt_12.js
call node ..\SCRIPT\Italy.txt_11.js
call node ..\SCRIPT\Italy.txt_10.js
call node ..\SCRIPT\Italy.txt_9.js
call node ..\SCRIPT\Italy.txt_8.js
call node ..\SCRIPT\Italy.txt_7.js
call node ..\SCRIPT\Italy.txt_6.js
call node ..\SCRIPT\Italy.txt_5.js
call node ..\SCRIPT\Italy.txt_4.js
call node ..\SCRIPT\Italy.txt_3.js
call node ..\SCRIPT\Italy.txt_2.js
call node ..\SCRIPT\Italy.txt_1.js

call node ..\SCRIPT\Spain.txt_15.js
call node ..\SCRIPT\Spain.txt_14.js
call node ..\SCRIPT\Spain.txt_13.js
call node ..\SCRIPT\Spain.txt_12.js
call node ..\SCRIPT\Spain.txt_11.js
call node ..\SCRIPT\Spain.txt_10.js
call node ..\SCRIPT\Spain.txt_9.js
call node ..\SCRIPT\Spain.txt_8.js
call node ..\SCRIPT\Spain.txt_7.js
call node ..\SCRIPT\Spain.txt_6.js
call node ..\SCRIPT\Spain.txt_5.js
call node ..\SCRIPT\Spain.txt_4.js
call node ..\SCRIPT\Spain.txt_3.js
call node ..\SCRIPT\Spain.txt_2.js
call node ..\SCRIPT\Spain.txt_1.js

call node ..\SCRIPT\Poland.txt_21.js
call node ..\SCRIPT\Poland.txt_20.js
call node ..\SCRIPT\Poland.txt_19.js
call node ..\SCRIPT\Poland.txt_18.js
call node ..\SCRIPT\Poland.txt_17.js
call node ..\SCRIPT\Poland.txt_16.js
call node ..\SCRIPT\Poland.txt_15.js
call node ..\SCRIPT\Poland.txt_14.js
call node ..\SCRIPT\Poland.txt_13.js
call node ..\SCRIPT\Poland.txt_12.js
call node ..\SCRIPT\Poland.txt_11.js
call node ..\SCRIPT\Poland.txt_10.js
call node ..\SCRIPT\Poland.txt_9.js
call node ..\SCRIPT\Poland.txt_8.js
call node ..\SCRIPT\Poland.txt_7.js
call node ..\SCRIPT\Poland.txt_6.js
call node ..\SCRIPT\Poland.txt_5.js
call node ..\SCRIPT\Poland.txt_4.js
call node ..\SCRIPT\Poland.txt_3.js
call node ..\SCRIPT\Poland.txt_2.js
call node ..\SCRIPT\Poland.txt_1.js

call node ..\SCRIPT\Mexico.txt_8.js
call node ..\SCRIPT\Mexico.txt_7.js
call node ..\SCRIPT\Mexico.txt_6.js
call node ..\SCRIPT\Mexico.txt_5.js
call node ..\SCRIPT\Mexico.txt_4.js
call node ..\SCRIPT\Mexico.txt_3.js
call node ..\SCRIPT\Mexico.txt_2.js
call node ..\SCRIPT\Mexico.txt_1.js

call node ..\SCRIPT\Argentina.txt_14.js
call node ..\SCRIPT\Argentina.txt_13.js
call node ..\SCRIPT\Argentina.txt_12.js
call node ..\SCRIPT\Argentina.txt_11.js
call node ..\SCRIPT\Argentina.txt_10.js
call node ..\SCRIPT\Argentina.txt_9.js
call node ..\SCRIPT\Argentina.txt_8.js
call node ..\SCRIPT\Argentina.txt_7.js
call node ..\SCRIPT\Argentina.txt_6.js
call node ..\SCRIPT\Argentina.txt_5.js
call node ..\SCRIPT\Argentina.txt_4.js
call node ..\SCRIPT\Argentina.txt_3.js
call node ..\SCRIPT\Argentina.txt_2.js
call node ..\SCRIPT\Argentina.txt_1.js

call node ..\SCRIPT\Armenia.txt_50.js
call node ..\SCRIPT\Armenia.txt_49.js
call node ..\SCRIPT\Armenia.txt_48.js
call node ..\SCRIPT\Armenia.txt_47.js
call node ..\SCRIPT\Armenia.txt_46.js
call node ..\SCRIPT\Armenia.txt_45.js
call node ..\SCRIPT\Armenia.txt_44.js
call node ..\SCRIPT\Armenia.txt_43.js
call node ..\SCRIPT\Armenia.txt_42.js
call node ..\SCRIPT\Armenia.txt_41.js
call node ..\SCRIPT\Armenia.txt_40.js
call node ..\SCRIPT\Armenia.txt_39.js
call node ..\SCRIPT\Armenia.txt_38.js
call node ..\SCRIPT\Armenia.txt_37.js
call node ..\SCRIPT\Armenia.txt_36.js
call node ..\SCRIPT\Armenia.txt_35.js
call node ..\SCRIPT\Armenia.txt_34.js
call node ..\SCRIPT\Armenia.txt_33.js
call node ..\SCRIPT\Armenia.txt_32.js
call node ..\SCRIPT\Armenia.txt_31.js
call node ..\SCRIPT\Armenia.txt_30.js
call node ..\SCRIPT\Armenia.txt_29.js
call node ..\SCRIPT\Armenia.txt_28.js
call node ..\SCRIPT\Armenia.txt_27.js
call node ..\SCRIPT\Armenia.txt_26.js
call node ..\SCRIPT\Armenia.txt_25.js
call node ..\SCRIPT\Armenia.txt_24.js
call node ..\SCRIPT\Armenia.txt_23.js
call node ..\SCRIPT\Armenia.txt_22.js
call node ..\SCRIPT\Armenia.txt_21.js
call node ..\SCRIPT\Armenia.txt_20.js
call node ..\SCRIPT\Armenia.txt_19.js
call node ..\SCRIPT\Armenia.txt_18.js
call node ..\SCRIPT\Armenia.txt_17.js
call node ..\SCRIPT\Armenia.txt_16.js
call node ..\SCRIPT\Armenia.txt_15.js
call node ..\SCRIPT\Armenia.txt_14.js
call node ..\SCRIPT\Armenia.txt_13.js
call node ..\SCRIPT\Armenia.txt_12.js
call node ..\SCRIPT\Armenia.txt_11.js
call node ..\SCRIPT\Armenia.txt_10.js
call node ..\SCRIPT\Armenia.txt_9.js
call node ..\SCRIPT\Armenia.txt_8.js
call node ..\SCRIPT\Armenia.txt_7.js
call node ..\SCRIPT\Armenia.txt_6.js
call node ..\SCRIPT\Armenia.txt_5.js
call node ..\SCRIPT\Armenia.txt_4.js
call node ..\SCRIPT\Armenia.txt_3.js
call node ..\SCRIPT\Armenia.txt_2.js
call node ..\SCRIPT\Armenia.txt_1.js

call node ..\SCRIPT\Israel.txt_4.js
call node ..\SCRIPT\Israel.txt_3.js
call node ..\SCRIPT\Israel.txt_2.js
call node ..\SCRIPT\Israel.txt_1.js

call node ..\SCRIPT\Netherland.txt_7.js
call node ..\SCRIPT\Netherland.txt_6.js
call node ..\SCRIPT\Netherland.txt_5.js
call node ..\SCRIPT\Netherland.txt_4.js
call node ..\SCRIPT\Netherland.txt_3.js
call node ..\SCRIPT\Netherland.txt_2.js
call node ..\SCRIPT\Netherland.txt_1.js

call node ..\SCRIPT\Afghanistan.txt_8.js
call node ..\SCRIPT\Afghanistan.txt_7.js
call node ..\SCRIPT\Afghanistan.txt_6.js
call node ..\SCRIPT\Afghanistan.txt_5.js
call node ..\SCRIPT\Afghanistan.txt_4.js
call node ..\SCRIPT\Afghanistan.txt_3.js
call node ..\SCRIPT\Afghanistan.txt_2.js
call node ..\SCRIPT\Afghanistan.txt_1.js

call node ..\SCRIPT\East_Timor.txt_6.js
call node ..\SCRIPT\East_Timor.txt_5.js
call node ..\SCRIPT\East_Timor.txt_4.js
call node ..\SCRIPT\East_Timor.txt_3.js
call node ..\SCRIPT\East_Timor.txt_2.js
call node ..\SCRIPT\East_Timor.txt_1.js

call node ..\SCRIPT\Cambodia.txt_14.js
call node ..\SCRIPT\Cambodia.txt_13.js
call node ..\SCRIPT\Cambodia.txt_12.js
call node ..\SCRIPT\Cambodia.txt_11.js
call node ..\SCRIPT\Cambodia.txt_10.js
call node ..\SCRIPT\Cambodia.txt_9.js
call node ..\SCRIPT\Cambodia.txt_8.js
call node ..\SCRIPT\Cambodia.txt_7.js
call node ..\SCRIPT\Cambodia.txt_6.js
call node ..\SCRIPT\Cambodia.txt_5.js
call node ..\SCRIPT\Cambodia.txt_4.js
call node ..\SCRIPT\Cambodia.txt_3.js
call node ..\SCRIPT\Cambodia.txt_2.js
call node ..\SCRIPT\Cambodia.txt_1.js

call node ..\SCRIPT\Georgia.txt_40.js
call node ..\SCRIPT\Georgia.txt_39.js
call node ..\SCRIPT\Georgia.txt_38.js
call node ..\SCRIPT\Georgia.txt_37.js
call node ..\SCRIPT\Georgia.txt_36.js
call node ..\SCRIPT\Georgia.txt_35.js
call node ..\SCRIPT\Georgia.txt_34.js
call node ..\SCRIPT\Georgia.txt_33.js
call node ..\SCRIPT\Georgia.txt_32.js
call node ..\SCRIPT\Georgia.txt_31.js
call node ..\SCRIPT\Georgia.txt_30.js
call node ..\SCRIPT\Georgia.txt_29.js
call node ..\SCRIPT\Georgia.txt_28.js
call node ..\SCRIPT\Georgia.txt_27.js
call node ..\SCRIPT\Georgia.txt_26.js
call node ..\SCRIPT\Georgia.txt_25.js
call node ..\SCRIPT\Georgia.txt_24.js
call node ..\SCRIPT\Georgia.txt_23.js
call node ..\SCRIPT\Georgia.txt_22.js
call node ..\SCRIPT\Georgia.txt_21.js
call node ..\SCRIPT\Georgia.txt_20.js
call node ..\SCRIPT\Georgia.txt_19.js
call node ..\SCRIPT\Georgia.txt_18.js
call node ..\SCRIPT\Georgia.txt_17.js
call node ..\SCRIPT\Georgia.txt_16.js
call node ..\SCRIPT\Georgia.txt_15.js
call node ..\SCRIPT\Georgia.txt_14.js
call node ..\SCRIPT\Georgia.txt_13.js
call node ..\SCRIPT\Georgia.txt_12.js
call node ..\SCRIPT\Georgia.txt_11.js
call node ..\SCRIPT\Georgia.txt_10.js
call node ..\SCRIPT\Georgia.txt_9.js
call node ..\SCRIPT\Georgia.txt_8.js
call node ..\SCRIPT\Georgia.txt_7.js
call node ..\SCRIPT\Georgia.txt_6.js
call node ..\SCRIPT\Georgia.txt_5.js
call node ..\SCRIPT\Georgia.txt_4.js
call node ..\SCRIPT\Georgia.txt_3.js
call node ..\SCRIPT\Georgia.txt_2.js
call node ..\SCRIPT\Georgia.txt_1.js

call node ..\SCRIPT\Cyprus.txt_33.js
call node ..\SCRIPT\Cyprus.txt_32.js
call node ..\SCRIPT\Cyprus.txt_31.js
call node ..\SCRIPT\Cyprus.txt_30.js
call node ..\SCRIPT\Cyprus.txt_29.js
call node ..\SCRIPT\Cyprus.txt_28.js
call node ..\SCRIPT\Cyprus.txt_27.js
call node ..\SCRIPT\Cyprus.txt_26.js
call node ..\SCRIPT\Cyprus.txt_25.js
call node ..\SCRIPT\Cyprus.txt_24.js
call node ..\SCRIPT\Cyprus.txt_23.js
call node ..\SCRIPT\Cyprus.txt_22.js
call node ..\SCRIPT\Cyprus.txt_21.js
call node ..\SCRIPT\Cyprus.txt_20.js
call node ..\SCRIPT\Cyprus.txt_19.js
call node ..\SCRIPT\Cyprus.txt_18.js
call node ..\SCRIPT\Cyprus.txt_17.js
call node ..\SCRIPT\Cyprus.txt_16.js
call node ..\SCRIPT\Cyprus.txt_15.js
call node ..\SCRIPT\Cyprus.txt_14.js
call node ..\SCRIPT\Cyprus.txt_13.js
call node ..\SCRIPT\Cyprus.txt_12.js
call node ..\SCRIPT\Cyprus.txt_11.js
call node ..\SCRIPT\Cyprus.txt_10.js
call node ..\SCRIPT\Cyprus.txt_9.js
call node ..\SCRIPT\Cyprus.txt_8.js
call node ..\SCRIPT\Cyprus.txt_7.js
call node ..\SCRIPT\Cyprus.txt_6.js
call node ..\SCRIPT\Cyprus.txt_5.js
call node ..\SCRIPT\Cyprus.txt_4.js
call node ..\SCRIPT\Cyprus.txt_3.js
call node ..\SCRIPT\Cyprus.txt_2.js
call node ..\SCRIPT\Cyprus.txt_1.js

call node ..\SCRIPT\Haiti.txt_9.js
call node ..\SCRIPT\Haiti.txt_8.js
call node ..\SCRIPT\Haiti.txt_7.js
call node ..\SCRIPT\Haiti.txt_6.js
call node ..\SCRIPT\Haiti.txt_5.js
call node ..\SCRIPT\Haiti.txt_4.js
call node ..\SCRIPT\Haiti.txt_3.js
call node ..\SCRIPT\Haiti.txt_2.js
call node ..\SCRIPT\Haiti.txt_1.js

call node ..\SCRIPT\Barbados.txt_7.js
call node ..\SCRIPT\Barbados.txt_6.js
call node ..\SCRIPT\Barbados.txt_5.js
call node ..\SCRIPT\Barbados.txt_4.js
call node ..\SCRIPT\Barbados.txt_3.js
call node ..\SCRIPT\Barbados.txt_2.js
call node ..\SCRIPT\Barbados.txt_1.js

call node ..\SCRIPT\Estonia.txt_24.js
call node ..\SCRIPT\Estonia.txt_23.js
call node ..\SCRIPT\Estonia.txt_22.js
call node ..\SCRIPT\Estonia.txt_21.js
call node ..\SCRIPT\Estonia.txt_20.js
call node ..\SCRIPT\Estonia.txt_19.js
call node ..\SCRIPT\Estonia.txt_18.js
call node ..\SCRIPT\Estonia.txt_17.js
call node ..\SCRIPT\Estonia.txt_16.js
call node ..\SCRIPT\Estonia.txt_15.js
call node ..\SCRIPT\Estonia.txt_14.js
call node ..\SCRIPT\Estonia.txt_13.js
call node ..\SCRIPT\Estonia.txt_12.js
call node ..\SCRIPT\Estonia.txt_11.js
call node ..\SCRIPT\Estonia.txt_10.js
call node ..\SCRIPT\Estonia.txt_9.js
call node ..\SCRIPT\Estonia.txt_8.js
call node ..\SCRIPT\Estonia.txt_7.js
call node ..\SCRIPT\Estonia.txt_6.js
call node ..\SCRIPT\Estonia.txt_5.js
call node ..\SCRIPT\Estonia.txt_4.js
call node ..\SCRIPT\Estonia.txt_3.js
call node ..\SCRIPT\Estonia.txt_2.js
call node ..\SCRIPT\Estonia.txt_1.js

call node ..\SCRIPT\Burundi.txt_6.js
call node ..\SCRIPT\Burundi.txt_5.js
call node ..\SCRIPT\Burundi.txt_4.js
call node ..\SCRIPT\Burundi.txt_3.js
call node ..\SCRIPT\Burundi.txt_2.js
call node ..\SCRIPT\Burundi.txt_1.js

call node ..\SCRIPT\Sweden.txt_21.js
call node ..\SCRIPT\Sweden.txt_20.js
call node ..\SCRIPT\Sweden.txt_19.js
call node ..\SCRIPT\Sweden.txt_18.js
call node ..\SCRIPT\Sweden.txt_17.js
call node ..\SCRIPT\Sweden.txt_16.js
call node ..\SCRIPT\Sweden.txt_15.js
call node ..\SCRIPT\Sweden.txt_14.js
call node ..\SCRIPT\Sweden.txt_13.js
call node ..\SCRIPT\Sweden.txt_12.js
call node ..\SCRIPT\Sweden.txt_11.js
call node ..\SCRIPT\Sweden.txt_10.js
call node ..\SCRIPT\Sweden.txt_9.js
call node ..\SCRIPT\Sweden.txt_8.js
call node ..\SCRIPT\Sweden.txt_7.js
call node ..\SCRIPT\Sweden.txt_6.js
call node ..\SCRIPT\Sweden.txt_5.js
call node ..\SCRIPT\Sweden.txt_4.js
call node ..\SCRIPT\Sweden.txt_3.js
call node ..\SCRIPT\Sweden.txt_2.js
call node ..\SCRIPT\Sweden.txt_1.js

call node ..\SCRIPT\Vietnam.txt_54.js
call node ..\SCRIPT\Vietnam.txt_53.js
call node ..\SCRIPT\Vietnam.txt_52.js
call node ..\SCRIPT\Vietnam.txt_51.js
call node ..\SCRIPT\Vietnam.txt_50.js
call node ..\SCRIPT\Vietnam.txt_49.js
call node ..\SCRIPT\Vietnam.txt_48.js
call node ..\SCRIPT\Vietnam.txt_47.js
call node ..\SCRIPT\Vietnam.txt_46.js
call node ..\SCRIPT\Vietnam.txt_45.js
call node ..\SCRIPT\Vietnam.txt_44.js
call node ..\SCRIPT\Vietnam.txt_43.js
call node ..\SCRIPT\Vietnam.txt_42.js
call node ..\SCRIPT\Vietnam.txt_41.js
call node ..\SCRIPT\Vietnam.txt_40.js
call node ..\SCRIPT\Vietnam.txt_39.js
call node ..\SCRIPT\Vietnam.txt_38.js
call node ..\SCRIPT\Vietnam.txt_37.js
call node ..\SCRIPT\Vietnam.txt_36.js
call node ..\SCRIPT\Vietnam.txt_35.js
call node ..\SCRIPT\Vietnam.txt_34.js
call node ..\SCRIPT\Vietnam.txt_33.js
call node ..\SCRIPT\Vietnam.txt_32.js
call node ..\SCRIPT\Vietnam.txt_31.js
call node ..\SCRIPT\Vietnam.txt_30.js
call node ..\SCRIPT\Vietnam.txt_29.js
call node ..\SCRIPT\Vietnam.txt_28.js
call node ..\SCRIPT\Vietnam.txt_27.js
call node ..\SCRIPT\Vietnam.txt_26.js
call node ..\SCRIPT\Vietnam.txt_25.js
call node ..\SCRIPT\Vietnam.txt_24.js
call node ..\SCRIPT\Vietnam.txt_23.js
call node ..\SCRIPT\Vietnam.txt_22.js
call node ..\SCRIPT\Vietnam.txt_21.js
call node ..\SCRIPT\Vietnam.txt_20.js
call node ..\SCRIPT\Vietnam.txt_19.js
call node ..\SCRIPT\Vietnam.txt_18.js
call node ..\SCRIPT\Vietnam.txt_17.js
call node ..\SCRIPT\Vietnam.txt_16.js
call node ..\SCRIPT\Vietnam.txt_15.js
call node ..\SCRIPT\Vietnam.txt_14.js
call node ..\SCRIPT\Vietnam.txt_13.js
call node ..\SCRIPT\Vietnam.txt_12.js
call node ..\SCRIPT\Vietnam.txt_11.js
call node ..\SCRIPT\Vietnam.txt_10.js
call node ..\SCRIPT\Vietnam.txt_9.js
call node ..\SCRIPT\Vietnam.txt_8.js
call node ..\SCRIPT\Vietnam.txt_7.js
call node ..\SCRIPT\Vietnam.txt_6.js
call node ..\SCRIPT\Vietnam.txt_5.js
call node ..\SCRIPT\Vietnam.txt_4.js
call node ..\SCRIPT\Vietnam.txt_3.js
call node ..\SCRIPT\Vietnam.txt_2.js
call node ..\SCRIPT\Vietnam.txt_1.js

call node ..\SCRIPT\Indinesia.txt_23.js
call node ..\SCRIPT\Indinesia.txt_22.js
call node ..\SCRIPT\Indinesia.txt_21.js
call node ..\SCRIPT\Indinesia.txt_20.js
call node ..\SCRIPT\Indinesia.txt_19.js
call node ..\SCRIPT\Indinesia.txt_18.js
call node ..\SCRIPT\Indinesia.txt_17.js
call node ..\SCRIPT\Indinesia.txt_16.js
call node ..\SCRIPT\Indinesia.txt_15.js
call node ..\SCRIPT\Indinesia.txt_14.js
call node ..\SCRIPT\Indinesia.txt_13.js
call node ..\SCRIPT\Indinesia.txt_12.js
call node ..\SCRIPT\Indinesia.txt_11.js
call node ..\SCRIPT\Indinesia.txt_10.js
call node ..\SCRIPT\Indinesia.txt_9.js
call node ..\SCRIPT\Indinesia.txt_8.js
call node ..\SCRIPT\Indinesia.txt_7.js
call node ..\SCRIPT\Indinesia.txt_6.js
call node ..\SCRIPT\Indinesia.txt_5.js
call node ..\SCRIPT\Indinesia.txt_4.js
call node ..\SCRIPT\Indinesia.txt_3.js
call node ..\SCRIPT\Indinesia.txt_2.js
call node ..\SCRIPT\Indinesia.txt_1.js

call node ..\SCRIPT\Yugoslovia.txt_29.js
call node ..\SCRIPT\Yugoslovia.txt_28.js
call node ..\SCRIPT\Yugoslovia.txt_27.js
call node ..\SCRIPT\Yugoslovia.txt_26.js
call node ..\SCRIPT\Yugoslovia.txt_25.js
call node ..\SCRIPT\Yugoslovia.txt_24.js
call node ..\SCRIPT\Yugoslovia.txt_23.js
call node ..\SCRIPT\Yugoslovia.txt_22.js
call node ..\SCRIPT\Yugoslovia.txt_21.js
call node ..\SCRIPT\Yugoslovia.txt_20.js
call node ..\SCRIPT\Yugoslovia.txt_19.js
call node ..\SCRIPT\Yugoslovia.txt_18.js
call node ..\SCRIPT\Yugoslovia.txt_17.js
call node ..\SCRIPT\Yugoslovia.txt_16.js
call node ..\SCRIPT\Yugoslovia.txt_15.js
call node ..\SCRIPT\Yugoslovia.txt_14.js
call node ..\SCRIPT\Yugoslovia.txt_13.js
call node ..\SCRIPT\Yugoslovia.txt_12.js
call node ..\SCRIPT\Yugoslovia.txt_11.js
call node ..\SCRIPT\Yugoslovia.txt_10.js
call node ..\SCRIPT\Yugoslovia.txt_9.js
call node ..\SCRIPT\Yugoslovia.txt_8.js
call node ..\SCRIPT\Yugoslovia.txt_7.js
call node ..\SCRIPT\Yugoslovia.txt_6.js
call node ..\SCRIPT\Yugoslovia.txt_5.js
call node ..\SCRIPT\Yugoslovia.txt_4.js
call node ..\SCRIPT\Yugoslovia.txt_3.js
call node ..\SCRIPT\Yugoslovia.txt_2.js
call node ..\SCRIPT\Yugoslovia.txt_1.js

call node ..\SCRIPT\Taiwan.txt_14.js
call node ..\SCRIPT\Taiwan.txt_13.js
call node ..\SCRIPT\Taiwan.txt_12.js
call node ..\SCRIPT\Taiwan.txt_11.js
call node ..\SCRIPT\Taiwan.txt_10.js
call node ..\SCRIPT\Taiwan.txt_9.js
call node ..\SCRIPT\Taiwan.txt_8.js
call node ..\SCRIPT\Taiwan.txt_7.js
call node ..\SCRIPT\Taiwan.txt_6.js
call node ..\SCRIPT\Taiwan.txt_5.js
call node ..\SCRIPT\Taiwan.txt_4.js
call node ..\SCRIPT\Taiwan.txt_3.js
call node ..\SCRIPT\Taiwan.txt_2.js
call node ..\SCRIPT\Taiwan.txt_1.js

call node ..\SCRIPT\Iceland.txt_16.js
call node ..\SCRIPT\Iceland.txt_15.js
call node ..\SCRIPT\Iceland.txt_14.js
call node ..\SCRIPT\Iceland.txt_13.js
call node ..\SCRIPT\Iceland.txt_12.js
call node ..\SCRIPT\Iceland.txt_11.js
call node ..\SCRIPT\Iceland.txt_10.js
call node ..\SCRIPT\Iceland.txt_9.js
call node ..\SCRIPT\Iceland.txt_8.js
call node ..\SCRIPT\Iceland.txt_7.js
call node ..\SCRIPT\Iceland.txt_6.js
call node ..\SCRIPT\Iceland.txt_5.js
call node ..\SCRIPT\Iceland.txt_4.js
call node ..\SCRIPT\Iceland.txt_3.js
call node ..\SCRIPT\Iceland.txt_2.js
call node ..\SCRIPT\Iceland.txt_1.js

call node ..\SCRIPT\Tanzania.txt_13.js
call node ..\SCRIPT\Tanzania.txt_12.js
call node ..\SCRIPT\Tanzania.txt_11.js
call node ..\SCRIPT\Tanzania.txt_10.js
call node ..\SCRIPT\Tanzania.txt_9.js
call node ..\SCRIPT\Tanzania.txt_8.js
call node ..\SCRIPT\Tanzania.txt_7.js
call node ..\SCRIPT\Tanzania.txt_6.js
call node ..\SCRIPT\Tanzania.txt_5.js
call node ..\SCRIPT\Tanzania.txt_4.js
call node ..\SCRIPT\Tanzania.txt_3.js
call node ..\SCRIPT\Tanzania.txt_2.js
call node ..\SCRIPT\Tanzania.txt_1.js

call node ..\SCRIPT\Russia.txt_19.js
call node ..\SCRIPT\Russia.txt_18.js
call node ..\SCRIPT\Russia.txt_17.js
call node ..\SCRIPT\Russia.txt_16.js
call node ..\SCRIPT\Russia.txt_15.js
call node ..\SCRIPT\Russia.txt_14.js
call node ..\SCRIPT\Russia.txt_13.js
call node ..\SCRIPT\Russia.txt_12.js
call node ..\SCRIPT\Russia.txt_11.js
call node ..\SCRIPT\Russia.txt_10.js
call node ..\SCRIPT\Russia.txt_9.js
call node ..\SCRIPT\Russia.txt_8.js
call node ..\SCRIPT\Russia.txt_7.js
call node ..\SCRIPT\Russia.txt_6.js
call node ..\SCRIPT\Russia.txt_5.js
call node ..\SCRIPT\Russia.txt_4.js
call node ..\SCRIPT\Russia.txt_3.js
call node ..\SCRIPT\Russia.txt_2.js
call node ..\SCRIPT\Russia.txt_1.js

call node ..\SCRIPT\Japan.txt_27.js
call node ..\SCRIPT\Japan.txt_26.js
call node ..\SCRIPT\Japan.txt_25.js
call node ..\SCRIPT\Japan.txt_24.js
call node ..\SCRIPT\Japan.txt_23.js
call node ..\SCRIPT\Japan.txt_22.js
call node ..\SCRIPT\Japan.txt_21.js
call node ..\SCRIPT\Japan.txt_20.js
call node ..\SCRIPT\Japan.txt_19.js
call node ..\SCRIPT\Japan.txt_18.js
call node ..\SCRIPT\Japan.txt_17.js
call node ..\SCRIPT\Japan.txt_16.js
call node ..\SCRIPT\Japan.txt_15.js
call node ..\SCRIPT\Japan.txt_14.js
call node ..\SCRIPT\Japan.txt_13.js
call node ..\SCRIPT\Japan.txt_12.js
call node ..\SCRIPT\Japan.txt_11.js
call node ..\SCRIPT\Japan.txt_10.js
call node ..\SCRIPT\Japan.txt_9.js
call node ..\SCRIPT\Japan.txt_8.js
call node ..\SCRIPT\Japan.txt_7.js
call node ..\SCRIPT\Japan.txt_6.js
call node ..\SCRIPT\Japan.txt_5.js
call node ..\SCRIPT\Japan.txt_4.js
call node ..\SCRIPT\Japan.txt_3.js
call node ..\SCRIPT\Japan.txt_2.js
call node ..\SCRIPT\Japan.txt_1.js

call node ..\SCRIPT\Ireland.txt_24.js
call node ..\SCRIPT\Ireland.txt_23.js
call node ..\SCRIPT\Ireland.txt_22.js
call node ..\SCRIPT\Ireland.txt_21.js
call node ..\SCRIPT\Ireland.txt_20.js
call node ..\SCRIPT\Ireland.txt_19.js
call node ..\SCRIPT\Ireland.txt_18.js
call node ..\SCRIPT\Ireland.txt_17.js
call node ..\SCRIPT\Ireland.txt_16.js
call node ..\SCRIPT\Ireland.txt_15.js
call node ..\SCRIPT\Ireland.txt_14.js
call node ..\SCRIPT\Ireland.txt_13.js
call node ..\SCRIPT\Ireland.txt_12.js
call node ..\SCRIPT\Ireland.txt_11.js
call node ..\SCRIPT\Ireland.txt_10.js
call node ..\SCRIPT\Ireland.txt_9.js
call node ..\SCRIPT\Ireland.txt_8.js
call node ..\SCRIPT\Ireland.txt_7.js
call node ..\SCRIPT\Ireland.txt_6.js
call node ..\SCRIPT\Ireland.txt_5.js
call node ..\SCRIPT\Ireland.txt_4.js
call node ..\SCRIPT\Ireland.txt_3.js
call node ..\SCRIPT\Ireland.txt_2.js
call node ..\SCRIPT\Ireland.txt_1.js

call node ..\SCRIPT\Chile.txt_9.js
call node ..\SCRIPT\Chile.txt_8.js
call node ..\SCRIPT\Chile.txt_7.js
call node ..\SCRIPT\Chile.txt_6.js
call node ..\SCRIPT\Chile.txt_5.js
call node ..\SCRIPT\Chile.txt_4.js
call node ..\SCRIPT\Chile.txt_3.js
call node ..\SCRIPT\Chile.txt_2.js
call node ..\SCRIPT\Chile.txt_1.js

call node ..\SCRIPT\Albania.txt_15.js
call node ..\SCRIPT\Albania.txt_14.js
call node ..\SCRIPT\Albania.txt_13.js
call node ..\SCRIPT\Albania.txt_12.js
call node ..\SCRIPT\Albania.txt_11.js
call node ..\SCRIPT\Albania.txt_10.js
call node ..\SCRIPT\Albania.txt_9.js
call node ..\SCRIPT\Albania.txt_8.js
call node ..\SCRIPT\Albania.txt_7.js
call node ..\SCRIPT\Albania.txt_6.js
call node ..\SCRIPT\Albania.txt_5.js
call node ..\SCRIPT\Albania.txt_4.js
call node ..\SCRIPT\Albania.txt_3.js
call node ..\SCRIPT\Albania.txt_2.js
call node ..\SCRIPT\Albania.txt_1.js

call node ..\SCRIPT\Bhutan.txt_18.js
call node ..\SCRIPT\Bhutan.txt_17.js
call node ..\SCRIPT\Bhutan.txt_16.js
call node ..\SCRIPT\Bhutan.txt_15.js
call node ..\SCRIPT\Bhutan.txt_14.js
call node ..\SCRIPT\Bhutan.txt_13.js
call node ..\SCRIPT\Bhutan.txt_12.js
call node ..\SCRIPT\Bhutan.txt_11.js
call node ..\SCRIPT\Bhutan.txt_10.js
call node ..\SCRIPT\Bhutan.txt_9.js
call node ..\SCRIPT\Bhutan.txt_8.js
call node ..\SCRIPT\Bhutan.txt_7.js
call node ..\SCRIPT\Bhutan.txt_6.js
call node ..\SCRIPT\Bhutan.txt_5.js
call node ..\SCRIPT\Bhutan.txt_4.js
call node ..\SCRIPT\Bhutan.txt_3.js
call node ..\SCRIPT\Bhutan.txt_2.js
call node ..\SCRIPT\Bhutan.txt_1.js

call node ..\SCRIPT\Burma.txt_40.js
call node ..\SCRIPT\Burma.txt_39.js
call node ..\SCRIPT\Burma.txt_38.js
call node ..\SCRIPT\Burma.txt_37.js
call node ..\SCRIPT\Burma.txt_36.js
call node ..\SCRIPT\Burma.txt_35.js
call node ..\SCRIPT\Burma.txt_34.js
call node ..\SCRIPT\Burma.txt_33.js
call node ..\SCRIPT\Burma.txt_32.js
call node ..\SCRIPT\Burma.txt_31.js
call node ..\SCRIPT\Burma.txt_30.js
call node ..\SCRIPT\Burma.txt_29.js
call node ..\SCRIPT\Burma.txt_28.js
call node ..\SCRIPT\Burma.txt_27.js
call node ..\SCRIPT\Burma.txt_26.js
call node ..\SCRIPT\Burma.txt_25.js
call node ..\SCRIPT\Burma.txt_24.js
call node ..\SCRIPT\Burma.txt_23.js
call node ..\SCRIPT\Burma.txt_22.js
call node ..\SCRIPT\Burma.txt_21.js
call node ..\SCRIPT\Burma.txt_20.js
call node ..\SCRIPT\Burma.txt_19.js
call node ..\SCRIPT\Burma.txt_18.js
call node ..\SCRIPT\Burma.txt_17.js
call node ..\SCRIPT\Burma.txt_16.js
call node ..\SCRIPT\Burma.txt_15.js
call node ..\SCRIPT\Burma.txt_14.js
call node ..\SCRIPT\Burma.txt_13.js
call node ..\SCRIPT\Burma.txt_12.js
call node ..\SCRIPT\Burma.txt_11.js
call node ..\SCRIPT\Burma.txt_10.js
call node ..\SCRIPT\Burma.txt_9.js
call node ..\SCRIPT\Burma.txt_8.js
call node ..\SCRIPT\Burma.txt_7.js
call node ..\SCRIPT\Burma.txt_6.js
call node ..\SCRIPT\Burma.txt_5.js
call node ..\SCRIPT\Burma.txt_4.js
call node ..\SCRIPT\Burma.txt_3.js
call node ..\SCRIPT\Burma.txt_2.js
call node ..\SCRIPT\Burma.txt_1.js

call node ..\SCRIPT\Bangladesh.txt_39.js
call node ..\SCRIPT\Bangladesh.txt_38.js
call node ..\SCRIPT\Bangladesh.txt_37.js
call node ..\SCRIPT\Bangladesh.txt_36.js
call node ..\SCRIPT\Bangladesh.txt_35.js
call node ..\SCRIPT\Bangladesh.txt_34.js
call node ..\SCRIPT\Bangladesh.txt_33.js
call node ..\SCRIPT\Bangladesh.txt_32.js
call node ..\SCRIPT\Bangladesh.txt_31.js
call node ..\SCRIPT\Bangladesh.txt_30.js
call node ..\SCRIPT\Bangladesh.txt_29.js
call node ..\SCRIPT\Bangladesh.txt_28.js
call node ..\SCRIPT\Bangladesh.txt_27.js
call node ..\SCRIPT\Bangladesh.txt_26.js
call node ..\SCRIPT\Bangladesh.txt_25.js
call node ..\SCRIPT\Bangladesh.txt_24.js
call node ..\SCRIPT\Bangladesh.txt_23.js
call node ..\SCRIPT\Bangladesh.txt_22.js
call node ..\SCRIPT\Bangladesh.txt_21.js
call node ..\SCRIPT\Bangladesh.txt_20.js
call node ..\SCRIPT\Bangladesh.txt_19.js
call node ..\SCRIPT\Bangladesh.txt_18.js
call node ..\SCRIPT\Bangladesh.txt_17.js
call node ..\SCRIPT\Bangladesh.txt_16.js
call node ..\SCRIPT\Bangladesh.txt_15.js
call node ..\SCRIPT\Bangladesh.txt_14.js
call node ..\SCRIPT\Bangladesh.txt_13.js
call node ..\SCRIPT\Bangladesh.txt_12.js
call node ..\SCRIPT\Bangladesh.txt_11.js
call node ..\SCRIPT\Bangladesh.txt_10.js
call node ..\SCRIPT\Bangladesh.txt_9.js
call node ..\SCRIPT\Bangladesh.txt_8.js
call node ..\SCRIPT\Bangladesh.txt_7.js
call node ..\SCRIPT\Bangladesh.txt_6.js
call node ..\SCRIPT\Bangladesh.txt_5.js
call node ..\SCRIPT\Bangladesh.txt_4.js
call node ..\SCRIPT\Bangladesh.txt_3.js
call node ..\SCRIPT\Bangladesh.txt_2.js
call node ..\SCRIPT\Bangladesh.txt_1.js

call node ..\SCRIPT\Cuba.txt_11.js
call node ..\SCRIPT\Cuba.txt_10.js
call node ..\SCRIPT\Cuba.txt_9.js
call node ..\SCRIPT\Cuba.txt_8.js
call node ..\SCRIPT\Cuba.txt_7.js
call node ..\SCRIPT\Cuba.txt_6.js
call node ..\SCRIPT\Cuba.txt_5.js
call node ..\SCRIPT\Cuba.txt_4.js
call node ..\SCRIPT\Cuba.txt_3.js
call node ..\SCRIPT\Cuba.txt_2.js
call node ..\SCRIPT\Cuba.txt_1.js

call node ..\SCRIPT\Canada.txt_19.js
call node ..\SCRIPT\Canada.txt_18.js
call node ..\SCRIPT\Canada.txt_17.js
call node ..\SCRIPT\Canada.txt_16.js
call node ..\SCRIPT\Canada.txt_15.js
call node ..\SCRIPT\Canada.txt_14.js
call node ..\SCRIPT\Canada.txt_13.js
call node ..\SCRIPT\Canada.txt_12.js
call node ..\SCRIPT\Canada.txt_11.js
call node ..\SCRIPT\Canada.txt_10.js
call node ..\SCRIPT\Canada.txt_9.js
call node ..\SCRIPT\Canada.txt_8.js
call node ..\SCRIPT\Canada.txt_7.js
call node ..\SCRIPT\Canada.txt_6.js
call node ..\SCRIPT\Canada.txt_5.js
call node ..\SCRIPT\Canada.txt_4.js
call node ..\SCRIPT\Canada.txt_3.js
call node ..\SCRIPT\Canada.txt_2.js
call node ..\SCRIPT\Canada.txt_1.js

call node ..\SCRIPT\USA.txt_12.js
call node ..\SCRIPT\USA.txt_11.js
call node ..\SCRIPT\USA.txt_10.js
call node ..\SCRIPT\USA.txt_9.js
call node ..\SCRIPT\USA.txt_8.js
call node ..\SCRIPT\USA.txt_7.js
call node ..\SCRIPT\USA.txt_6.js
call node ..\SCRIPT\USA.txt_5.js
call node ..\SCRIPT\USA.txt_4.js
call node ..\SCRIPT\USA.txt_3.js
call node ..\SCRIPT\USA.txt_2.js
call node ..\SCRIPT\USA.txt_1.js

call node ..\SCRIPT\England.txt_25.js
call node ..\SCRIPT\England.txt_24.js
call node ..\SCRIPT\England.txt_23.js
call node ..\SCRIPT\England.txt_22.js
call node ..\SCRIPT\England.txt_21.js
call node ..\SCRIPT\England.txt_20.js
call node ..\SCRIPT\England.txt_19.js
call node ..\SCRIPT\England.txt_18.js
call node ..\SCRIPT\England.txt_17.js
call node ..\SCRIPT\England.txt_16.js
call node ..\SCRIPT\England.txt_15.js
call node ..\SCRIPT\England.txt_14.js
call node ..\SCRIPT\England.txt_13.js
call node ..\SCRIPT\England.txt_12.js
call node ..\SCRIPT\England.txt_11.js
call node ..\SCRIPT\England.txt_10.js
call node ..\SCRIPT\England.txt_9.js
call node ..\SCRIPT\England.txt_8.js
call node ..\SCRIPT\England.txt_7.js
call node ..\SCRIPT\England.txt_6.js
call node ..\SCRIPT\England.txt_5.js
call node ..\SCRIPT\England.txt_4.js
call node ..\SCRIPT\England.txt_3.js
call node ..\SCRIPT\England.txt_2.js
call node ..\SCRIPT\England.txt_1.js

call node ..\SCRIPT\Australia.txt_8.js
call node ..\SCRIPT\Australia.txt_7.js
call node ..\SCRIPT\Australia.txt_6.js
call node ..\SCRIPT\Australia.txt_5.js
call node ..\SCRIPT\Australia.txt_4.js
call node ..\SCRIPT\Australia.txt_3.js
call node ..\SCRIPT\Australia.txt_2.js
call node ..\SCRIPT\Australia.txt_1.js

call node ..\SCRIPT\Germany.txt_23.js
call node ..\SCRIPT\Germany.txt_22.js
call node ..\SCRIPT\Germany.txt_21.js
call node ..\SCRIPT\Germany.txt_20.js
call node ..\SCRIPT\Germany.txt_19.js
call node ..\SCRIPT\Germany.txt_18.js
call node ..\SCRIPT\Germany.txt_17.js
call node ..\SCRIPT\Germany.txt_16.js
call node ..\SCRIPT\Germany.txt_15.js
call node ..\SCRIPT\Germany.txt_14.js
call node ..\SCRIPT\Germany.txt_13.js
call node ..\SCRIPT\Germany.txt_12.js
call node ..\SCRIPT\Germany.txt_11.js
call node ..\SCRIPT\Germany.txt_10.js
call node ..\SCRIPT\Germany.txt_9.js
call node ..\SCRIPT\Germany.txt_8.js
call node ..\SCRIPT\Germany.txt_7.js
call node ..\SCRIPT\Germany.txt_6.js
call node ..\SCRIPT\Germany.txt_5.js
call node ..\SCRIPT\Germany.txt_4.js
call node ..\SCRIPT\Germany.txt_3.js
call node ..\SCRIPT\Germany.txt_2.js
call node ..\SCRIPT\Germany.txt_1.js

call node ..\SCRIPT\Belgium.txt_28.js
call node ..\SCRIPT\Belgium.txt_27.js
call node ..\SCRIPT\Belgium.txt_26.js
call node ..\SCRIPT\Belgium.txt_25.js
call node ..\SCRIPT\Belgium.txt_24.js
call node ..\SCRIPT\Belgium.txt_23.js
call node ..\SCRIPT\Belgium.txt_22.js
call node ..\SCRIPT\Belgium.txt_21.js
call node ..\SCRIPT\Belgium.txt_20.js
call node ..\SCRIPT\Belgium.txt_19.js
call node ..\SCRIPT\Belgium.txt_18.js
call node ..\SCRIPT\Belgium.txt_17.js
call node ..\SCRIPT\Belgium.txt_16.js
call node ..\SCRIPT\Belgium.txt_15.js
call node ..\SCRIPT\Belgium.txt_14.js
call node ..\SCRIPT\Belgium.txt_13.js
call node ..\SCRIPT\Belgium.txt_12.js
call node ..\SCRIPT\Belgium.txt_11.js
call node ..\SCRIPT\Belgium.txt_10.js
call node ..\SCRIPT\Belgium.txt_9.js
call node ..\SCRIPT\Belgium.txt_8.js
call node ..\SCRIPT\Belgium.txt_7.js
call node ..\SCRIPT\Belgium.txt_6.js
call node ..\SCRIPT\Belgium.txt_5.js
call node ..\SCRIPT\Belgium.txt_4.js
call node ..\SCRIPT\Belgium.txt_3.js
call node ..\SCRIPT\Belgium.txt_2.js
call node ..\SCRIPT\Belgium.txt_1.js

call node ..\SCRIPT\Colombia.txt_22.js
call node ..\SCRIPT\Colombia.txt_21.js
call node ..\SCRIPT\Colombia.txt_20.js
call node ..\SCRIPT\Colombia.txt_19.js
call node ..\SCRIPT\Colombia.txt_18.js
call node ..\SCRIPT\Colombia.txt_17.js
call node ..\SCRIPT\Colombia.txt_16.js
call node ..\SCRIPT\Colombia.txt_15.js
call node ..\SCRIPT\Colombia.txt_14.js
call node ..\SCRIPT\Colombia.txt_13.js
call node ..\SCRIPT\Colombia.txt_12.js
call node ..\SCRIPT\Colombia.txt_11.js
call node ..\SCRIPT\Colombia.txt_10.js
call node ..\SCRIPT\Colombia.txt_9.js
call node ..\SCRIPT\Colombia.txt_8.js
call node ..\SCRIPT\Colombia.txt_7.js
call node ..\SCRIPT\Colombia.txt_6.js
call node ..\SCRIPT\Colombia.txt_5.js
call node ..\SCRIPT\Colombia.txt_4.js
call node ..\SCRIPT\Colombia.txt_3.js
call node ..\SCRIPT\Colombia.txt_2.js
call node ..\SCRIPT\Colombia.txt_1.js

call node ..\SCRIPT\India.txt_42.js
call node ..\SCRIPT\India.txt_41.js
call node ..\SCRIPT\India.txt_40.js
call node ..\SCRIPT\India.txt_39.js
call node ..\SCRIPT\India.txt_38.js
call node ..\SCRIPT\India.txt_37.js
call node ..\SCRIPT\India.txt_36.js
call node ..\SCRIPT\India.txt_35.js
call node ..\SCRIPT\India.txt_34.js
call node ..\SCRIPT\India.txt_33.js
call node ..\SCRIPT\India.txt_32.js
call node ..\SCRIPT\India.txt_31.js
call node ..\SCRIPT\India.txt_30.js
call node ..\SCRIPT\India.txt_29.js
call node ..\SCRIPT\India.txt_28.js
call node ..\SCRIPT\India.txt_27.js
call node ..\SCRIPT\India.txt_26.js
call node ..\SCRIPT\India.txt_25.js
call node ..\SCRIPT\India.txt_24.js
call node ..\SCRIPT\India.txt_23.js
call node ..\SCRIPT\India.txt_22.js
call node ..\SCRIPT\India.txt_21.js
call node ..\SCRIPT\India.txt_20.js
call node ..\SCRIPT\India.txt_19.js
call node ..\SCRIPT\India.txt_18.js
call node ..\SCRIPT\India.txt_17.js
call node ..\SCRIPT\India.txt_16.js
call node ..\SCRIPT\India.txt_15.js
call node ..\SCRIPT\India.txt_14.js
call node ..\SCRIPT\India.txt_13.js
call node ..\SCRIPT\India.txt_12.js
call node ..\SCRIPT\India.txt_11.js
call node ..\SCRIPT\India.txt_10.js
call node ..\SCRIPT\India.txt_9.js
call node ..\SCRIPT\India.txt_8.js
call node ..\SCRIPT\India.txt_7.js
call node ..\SCRIPT\India.txt_6.js
call node ..\SCRIPT\India.txt_5.js
call node ..\SCRIPT\India.txt_4.js
call node ..\SCRIPT\India.txt_3.js
call node ..\SCRIPT\India.txt_2.js
call node ..\SCRIPT\India.txt_1.js

call node ..\SCRIPT\China.txt_55.js
call node ..\SCRIPT\China.txt_54.js
call node ..\SCRIPT\China.txt_53.js
call node ..\SCRIPT\China.txt_52.js
call node ..\SCRIPT\China.txt_51.js
call node ..\SCRIPT\China.txt_50.js
call node ..\SCRIPT\China.txt_49.js
call node ..\SCRIPT\China.txt_48.js
call node ..\SCRIPT\China.txt_47.js
call node ..\SCRIPT\China.txt_46.js
call node ..\SCRIPT\China.txt_45.js
call node ..\SCRIPT\China.txt_44.js
call node ..\SCRIPT\China.txt_43.js
call node ..\SCRIPT\China.txt_42.js
call node ..\SCRIPT\China.txt_41.js
call node ..\SCRIPT\China.txt_40.js
call node ..\SCRIPT\China.txt_39.js
call node ..\SCRIPT\China.txt_38.js
call node ..\SCRIPT\China.txt_37.js
call node ..\SCRIPT\China.txt_36.js
call node ..\SCRIPT\China.txt_35.js
call node ..\SCRIPT\China.txt_34.js
call node ..\SCRIPT\China.txt_33.js
call node ..\SCRIPT\China.txt_32.js
call node ..\SCRIPT\China.txt_31.js
call node ..\SCRIPT\China.txt_30.js
call node ..\SCRIPT\China.txt_29.js
call node ..\SCRIPT\China.txt_28.js
call node ..\SCRIPT\China.txt_27.js
call node ..\SCRIPT\China.txt_26.js
call node ..\SCRIPT\China.txt_25.js
call node ..\SCRIPT\China.txt_24.js
call node ..\SCRIPT\China.txt_23.js
call node ..\SCRIPT\China.txt_22.js
call node ..\SCRIPT\China.txt_21.js
call node ..\SCRIPT\China.txt_20.js
call node ..\SCRIPT\China.txt_19.js
call node ..\SCRIPT\China.txt_18.js
call node ..\SCRIPT\China.txt_17.js
call node ..\SCRIPT\China.txt_16.js
call node ..\SCRIPT\China.txt_15.js
call node ..\SCRIPT\China.txt_14.js
call node ..\SCRIPT\China.txt_13.js
call node ..\SCRIPT\China.txt_12.js
call node ..\SCRIPT\China.txt_11.js
call node ..\SCRIPT\China.txt_10.js
call node ..\SCRIPT\China.txt_9.js
call node ..\SCRIPT\China.txt_8.js
call node ..\SCRIPT\China.txt_7.js
call node ..\SCRIPT\China.txt_6.js
call node ..\SCRIPT\China.txt_5.js
call node ..\SCRIPT\China.txt_4.js
call node ..\SCRIPT\China.txt_3.js
call node ..\SCRIPT\China.txt_2.js
call node ..\SCRIPT\China.txt_1.js

call node ..\SCRIPT\geopolitical_change.txt_121.js
call node ..\SCRIPT\geopolitical_change.txt_120.js
call node ..\SCRIPT\geopolitical_change.txt_119.js
call node ..\SCRIPT\geopolitical_change.txt_118.js
call node ..\SCRIPT\geopolitical_change.txt_117.js
call node ..\SCRIPT\geopolitical_change.txt_116.js
call node ..\SCRIPT\geopolitical_change.txt_115.js
call node ..\SCRIPT\geopolitical_change.txt_114.js
call node ..\SCRIPT\geopolitical_change.txt_113.js
call node ..\SCRIPT\geopolitical_change.txt_112.js
call node ..\SCRIPT\geopolitical_change.txt_111.js
call node ..\SCRIPT\geopolitical_change.txt_110.js
call node ..\SCRIPT\geopolitical_change.txt_109.js
call node ..\SCRIPT\geopolitical_change.txt_108.js
call node ..\SCRIPT\geopolitical_change.txt_107.js
call node ..\SCRIPT\geopolitical_change.txt_106.js
call node ..\SCRIPT\geopolitical_change.txt_105.js
call node ..\SCRIPT\geopolitical_change.txt_104.js
call node ..\SCRIPT\geopolitical_change.txt_103.js
call node ..\SCRIPT\geopolitical_change.txt_102.js
call node ..\SCRIPT\geopolitical_change.txt_101.js
call node ..\SCRIPT\geopolitical_change.txt_100.js
call node ..\SCRIPT\geopolitical_change.txt_99.js
call node ..\SCRIPT\geopolitical_change.txt_98.js
call node ..\SCRIPT\geopolitical_change.txt_97.js
call node ..\SCRIPT\geopolitical_change.txt_96.js
call node ..\SCRIPT\geopolitical_change.txt_95.js
call node ..\SCRIPT\geopolitical_change.txt_94.js
call node ..\SCRIPT\geopolitical_change.txt_93.js
call node ..\SCRIPT\geopolitical_change.txt_92.js
call node ..\SCRIPT\geopolitical_change.txt_91.js
call node ..\SCRIPT\geopolitical_change.txt_90.js
call node ..\SCRIPT\geopolitical_change.txt_89.js
call node ..\SCRIPT\geopolitical_change.txt_88.js
call node ..\SCRIPT\geopolitical_change.txt_87.js
call node ..\SCRIPT\geopolitical_change.txt_86.js
call node ..\SCRIPT\geopolitical_change.txt_85.js
call node ..\SCRIPT\geopolitical_change.txt_84.js
call node ..\SCRIPT\geopolitical_change.txt_83.js
call node ..\SCRIPT\geopolitical_change.txt_82.js
call node ..\SCRIPT\geopolitical_change.txt_81.js
call node ..\SCRIPT\geopolitical_change.txt_80.js
call node ..\SCRIPT\geopolitical_change.txt_79.js
call node ..\SCRIPT\geopolitical_change.txt_78.js
call node ..\SCRIPT\geopolitical_change.txt_77.js
call node ..\SCRIPT\geopolitical_change.txt_76.js
call node ..\SCRIPT\geopolitical_change.txt_75.js
call node ..\SCRIPT\geopolitical_change.txt_74.js
call node ..\SCRIPT\geopolitical_change.txt_73.js
call node ..\SCRIPT\geopolitical_change.txt_72.js
call node ..\SCRIPT\geopolitical_change.txt_71.js
call node ..\SCRIPT\geopolitical_change.txt_70.js
call node ..\SCRIPT\geopolitical_change.txt_69.js
call node ..\SCRIPT\geopolitical_change.txt_68.js
call node ..\SCRIPT\geopolitical_change.txt_67.js
call node ..\SCRIPT\geopolitical_change.txt_66.js
call node ..\SCRIPT\geopolitical_change.txt_65.js
call node ..\SCRIPT\geopolitical_change.txt_64.js
call node ..\SCRIPT\geopolitical_change.txt_63.js
call node ..\SCRIPT\geopolitical_change.txt_62.js
call node ..\SCRIPT\geopolitical_change.txt_61.js
call node ..\SCRIPT\geopolitical_change.txt_60.js
call node ..\SCRIPT\geopolitical_change.txt_59.js
call node ..\SCRIPT\geopolitical_change.txt_58.js
call node ..\SCRIPT\geopolitical_change.txt_57.js
call node ..\SCRIPT\geopolitical_change.txt_56.js
call node ..\SCRIPT\geopolitical_change.txt_55.js
call node ..\SCRIPT\geopolitical_change.txt_54.js
call node ..\SCRIPT\geopolitical_change.txt_53.js
call node ..\SCRIPT\geopolitical_change.txt_52.js
call node ..\SCRIPT\geopolitical_change.txt_51.js
call node ..\SCRIPT\geopolitical_change.txt_50.js
call node ..\SCRIPT\geopolitical_change.txt_49.js
call node ..\SCRIPT\geopolitical_change.txt_48.js
call node ..\SCRIPT\geopolitical_change.txt_47.js
call node ..\SCRIPT\geopolitical_change.txt_46.js
call node ..\SCRIPT\geopolitical_change.txt_45.js
call node ..\SCRIPT\geopolitical_change.txt_44.js
call node ..\SCRIPT\geopolitical_change.txt_43.js
call node ..\SCRIPT\geopolitical_change.txt_42.js
call node ..\SCRIPT\geopolitical_change.txt_41.js
call node ..\SCRIPT\geopolitical_change.txt_40.js
call node ..\SCRIPT\geopolitical_change.txt_39.js
call node ..\SCRIPT\geopolitical_change.txt_38.js
call node ..\SCRIPT\geopolitical_change.txt_37.js
call node ..\SCRIPT\geopolitical_change.txt_36.js
call node ..\SCRIPT\geopolitical_change.txt_35.js
call node ..\SCRIPT\geopolitical_change.txt_34.js
call node ..\SCRIPT\geopolitical_change.txt_33.js
call node ..\SCRIPT\geopolitical_change.txt_32.js
call node ..\SCRIPT\geopolitical_change.txt_31.js
call node ..\SCRIPT\geopolitical_change.txt_30.js
call node ..\SCRIPT\geopolitical_change.txt_29.js
call node ..\SCRIPT\geopolitical_change.txt_28.js
call node ..\SCRIPT\geopolitical_change.txt_27.js
call node ..\SCRIPT\geopolitical_change.txt_26.js
call node ..\SCRIPT\geopolitical_change.txt_25.js
call node ..\SCRIPT\geopolitical_change.txt_24.js
call node ..\SCRIPT\geopolitical_change.txt_23.js
call node ..\SCRIPT\geopolitical_change.txt_22.js
call node ..\SCRIPT\geopolitical_change.txt_21.js
call node ..\SCRIPT\geopolitical_change.txt_20.js
call node ..\SCRIPT\geopolitical_change.txt_19.js
call node ..\SCRIPT\geopolitical_change.txt_18.js
call node ..\SCRIPT\geopolitical_change.txt_17.js
call node ..\SCRIPT\geopolitical_change.txt_16.js
call node ..\SCRIPT\geopolitical_change.txt_15.js
call node ..\SCRIPT\geopolitical_change.txt_14.js
call node ..\SCRIPT\geopolitical_change.txt_13.js
call node ..\SCRIPT\geopolitical_change.txt_12.js
call node ..\SCRIPT\geopolitical_change.txt_11.js
call node ..\SCRIPT\geopolitical_change.txt_10.js
call node ..\SCRIPT\geopolitical_change.txt_9.js
call node ..\SCRIPT\geopolitical_change.txt_8.js
call node ..\SCRIPT\geopolitical_change.txt_7.js
call node ..\SCRIPT\geopolitical_change.txt_6.js
call node ..\SCRIPT\geopolitical_change.txt_5.js
call node ..\SCRIPT\geopolitical_change.txt_4.js
call node ..\SCRIPT\geopolitical_change.txt_3.js
call node ..\SCRIPT\geopolitical_change.txt_2.js
call node ..\SCRIPT\geopolitical_change.txt_1.js

call node ..\SCRIPT\Philippine.txt_26.js
call node ..\SCRIPT\Philippine.txt_25.js
call node ..\SCRIPT\Philippine.txt_24.js
call node ..\SCRIPT\Philippine.txt_23.js
call node ..\SCRIPT\Philippine.txt_22.js
call node ..\SCRIPT\Philippine.txt_21.js
call node ..\SCRIPT\Philippine.txt_20.js
call node ..\SCRIPT\Philippine.txt_19.js
call node ..\SCRIPT\Philippine.txt_18.js
call node ..\SCRIPT\Philippine.txt_17.js
call node ..\SCRIPT\Philippine.txt_16.js
call node ..\SCRIPT\Philippine.txt_15.js
call node ..\SCRIPT\Philippine.txt_14.js
call node ..\SCRIPT\Philippine.txt_13.js
call node ..\SCRIPT\Philippine.txt_12.js
call node ..\SCRIPT\Philippine.txt_11.js
call node ..\SCRIPT\Philippine.txt_10.js
call node ..\SCRIPT\Philippine.txt_9.js
call node ..\SCRIPT\Philippine.txt_8.js
call node ..\SCRIPT\Philippine.txt_7.js
call node ..\SCRIPT\Philippine.txt_6.js
call node ..\SCRIPT\Philippine.txt_5.js
call node ..\SCRIPT\Philippine.txt_4.js
call node ..\SCRIPT\Philippine.txt_3.js
call node ..\SCRIPT\Philippine.txt_2.js
call node ..\SCRIPT\Philippine.txt_1.js

call node ..\SCRIPT\Brazil.txt_11.js
call node ..\SCRIPT\Brazil.txt_10.js
call node ..\SCRIPT\Brazil.txt_9.js
call node ..\SCRIPT\Brazil.txt_8.js
call node ..\SCRIPT\Brazil.txt_7.js
call node ..\SCRIPT\Brazil.txt_6.js
call node ..\SCRIPT\Brazil.txt_5.js
call node ..\SCRIPT\Brazil.txt_4.js
call node ..\SCRIPT\Brazil.txt_3.js
call node ..\SCRIPT\Brazil.txt_2.js
call node ..\SCRIPT\Brazil.txt_1.js
