call cd SCRIPT
call npm install
call cd ..
call md DOWNLOADED_DATA
call cd DOWNLOADED_DATA


call node ..\SCRIPT\Afghanistan.js
call node ..\SCRIPT\Albania.js
call node ..\SCRIPT\Argentina.js
call node ..\SCRIPT\Armenia.js
call node ..\SCRIPT\Australia.js
call node ..\SCRIPT\Bangladesh.js
call node ..\SCRIPT\Barbados.js
call node ..\SCRIPT\Belgium.js
call node ..\SCRIPT\Bhutan.js
call node ..\SCRIPT\Brazil.js
call node ..\SCRIPT\England.js
call node ..\SCRIPT\Burma.js
call node ..\SCRIPT\Burundi.js
call node ..\SCRIPT\Cambodia.js
call node ..\SCRIPT\Canada.js
call node ..\SCRIPT\Chile.js
call node ..\SCRIPT\China.js
call node ..\SCRIPT\Colombia.js
call node ..\SCRIPT\Cuba.js
call node ..\SCRIPT\Cyprus.js
call node ..\SCRIPT\East_Timor.js
call node ..\SCRIPT\Estonia.js
call node ..\SCRIPT\France.js
call node ..\SCRIPT\Germany.js
call node ..\SCRIPT\Haiti.js
call node ..\SCRIPT\India.js
call node ..\SCRIPT\Indinesia.js
call node ..\SCRIPT\Ireland.js
call node ..\SCRIPT\Israel.js
call node ..\SCRIPT\Italy.js
call node ..\SCRIPT\Japan.js
call node ..\SCRIPT\Kenya.js
call node ..\SCRIPT\Latvia.js
call node ..\SCRIPT\Lebanon.js
call node ..\SCRIPT\Malaysia.js
call node ..\SCRIPT\Malta.js
call node ..\SCRIPT\Mexico.js
call node ..\SCRIPT\Nepal.js
call node ..\SCRIPT\Peru.js
call node ..\SCRIPT\Philippine.js
call node ..\SCRIPT\Poland.js
call node ..\SCRIPT\Russia.js
call node ..\SCRIPT\Rwanda.js
call node ..\SCRIPT\Serbia.js
call node ..\SCRIPT\Singapore.js
call node ..\SCRIPT\Slovenia.js
call node ..\SCRIPT\Spain.js
call node ..\SCRIPT\Sudan.js
call node ..\SCRIPT\Sweden.js
call node ..\SCRIPT\Switzerland.js
call node ..\SCRIPT\Syria.js
call node ..\SCRIPT\Taiwan.js
call node ..\SCRIPT\Tajikistan.js
call node ..\SCRIPT\Tanzania.js
call node ..\SCRIPT\Tonga.js
call node ..\SCRIPT\Vietnam.js
call node ..\SCRIPT\USA.js
