call cd SCRIPT
call npm install
call cd ..
call md DOWNLOADED_DATA
call cd DOWNLOADED_DATA


call node ..\SCRIPT\india.txt_42.js
call node ..\SCRIPT\india.txt_41.js
call node ..\SCRIPT\india.txt_40.js
call node ..\SCRIPT\india.txt_39.js
call node ..\SCRIPT\india.txt_38.js
call node ..\SCRIPT\india.txt_37.js
call node ..\SCRIPT\india.txt_36.js
call node ..\SCRIPT\india.txt_35.js
call node ..\SCRIPT\india.txt_34.js
call node ..\SCRIPT\india.txt_33.js
call node ..\SCRIPT\india.txt_32.js
call node ..\SCRIPT\india.txt_31.js
call node ..\SCRIPT\india.txt_30.js
call node ..\SCRIPT\india.txt_29.js
call node ..\SCRIPT\india.txt_28.js
call node ..\SCRIPT\india.txt_27.js
call node ..\SCRIPT\india.txt_26.js
call node ..\SCRIPT\india.txt_25.js
call node ..\SCRIPT\india.txt_24.js
call node ..\SCRIPT\india.txt_23.js
call node ..\SCRIPT\india.txt_22.js
call node ..\SCRIPT\india.txt_21.js
call node ..\SCRIPT\india.txt_20.js
call node ..\SCRIPT\india.txt_19.js
call node ..\SCRIPT\india.txt_18.js
call node ..\SCRIPT\india.txt_17.js
call node ..\SCRIPT\india.txt_16.js
call node ..\SCRIPT\india.txt_15.js
call node ..\SCRIPT\india.txt_14.js
call node ..\SCRIPT\india.txt_13.js
call node ..\SCRIPT\india.txt_12.js
call node ..\SCRIPT\india.txt_11.js
call node ..\SCRIPT\india.txt_10.js
call node ..\SCRIPT\india.txt_9.js
call node ..\SCRIPT\india.txt_8.js
call node ..\SCRIPT\india.txt_7.js
call node ..\SCRIPT\india.txt_6.js
call node ..\SCRIPT\india.txt_5.js
call node ..\SCRIPT\india.txt_4.js
call node ..\SCRIPT\india.txt_3.js
call node ..\SCRIPT\india.txt_2.js
call node ..\SCRIPT\india.txt_1.js

call node ..\SCRIPT\USA.txt_12.js
call node ..\SCRIPT\USA.txt_11.js
call node ..\SCRIPT\USA.txt_10.js
call node ..\SCRIPT\USA.txt_9.js
call node ..\SCRIPT\USA.txt_8.js
call node ..\SCRIPT\USA.txt_7.js
call node ..\SCRIPT\USA.txt_6.js
call node ..\SCRIPT\USA.txt_5.js
call node ..\SCRIPT\USA.txt_4.js
call node ..\SCRIPT\USA.txt_3.js
call node ..\SCRIPT\USA.txt_2.js
call node ..\SCRIPT\USA.txt_1.js
